[2025-09-08 16:27:40 +0300] [26598] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:27:40 +0300] [26598] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:40 +0300] [26598] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:41 +0300] [26598] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:41 +0300] [26598] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:42 +0300] [26598] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:42 +0300] [26598] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:43 +0300] [26598] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:43 +0300] [26598] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:44 +0300] [26598] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:44 +0300] [26598] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:45 +0300] [26598] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:27:55 +0300] [26757] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:27:55 +0300] [26757] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:55 +0300] [26757] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:56 +0300] [26757] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:56 +0300] [26757] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:57 +0300] [26757] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:57 +0300] [26757] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:58 +0300] [26757] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:58 +0300] [26757] [ERROR] Retrying in 1 second.
[2025-09-08 16:27:59 +0300] [26757] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:27:59 +0300] [26757] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:00 +0300] [26757] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:28:10 +0300] [26854] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:28:10 +0300] [26854] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:10 +0300] [26854] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:11 +0300] [26854] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:11 +0300] [26854] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:12 +0300] [26854] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:12 +0300] [26854] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:13 +0300] [26854] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:13 +0300] [26854] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:14 +0300] [26854] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:14 +0300] [26854] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:15 +0300] [26854] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:28:26 +0300] [27015] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:28:26 +0300] [27015] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:26 +0300] [27015] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:27 +0300] [27015] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:27 +0300] [27015] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:28 +0300] [27015] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:28 +0300] [27015] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:29 +0300] [27015] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:29 +0300] [27015] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:30 +0300] [27015] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:30 +0300] [27015] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:31 +0300] [27015] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:28:41 +0300] [27188] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:28:41 +0300] [27188] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:41 +0300] [27188] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:42 +0300] [27188] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:42 +0300] [27188] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:43 +0300] [27188] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:43 +0300] [27188] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:44 +0300] [27188] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:44 +0300] [27188] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:45 +0300] [27188] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:45 +0300] [27188] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:46 +0300] [27188] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:28:46 +0300] [27243] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:28:46 +0300] [27243] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:46 +0300] [27243] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:47 +0300] [27243] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:47 +0300] [27243] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:48 +0300] [27243] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:48 +0300] [27243] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:49 +0300] [27243] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:49 +0300] [27243] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:50 +0300] [27243] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:28:50 +0300] [27243] [ERROR] Retrying in 1 second.
[2025-09-08 16:28:51 +0300] [27243] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:29:01 +0300] [27377] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:29:01 +0300] [27377] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:01 +0300] [27377] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:02 +0300] [27377] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:02 +0300] [27377] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:03 +0300] [27377] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:03 +0300] [27377] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:04 +0300] [27377] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:04 +0300] [27377] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:05 +0300] [27377] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:05 +0300] [27377] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:06 +0300] [27377] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:29:12 +0300] [27516] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:29:12 +0300] [27516] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:12 +0300] [27516] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:13 +0300] [27516] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:13 +0300] [27516] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:14 +0300] [27516] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:14 +0300] [27516] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:15 +0300] [27516] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:15 +0300] [27516] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:16 +0300] [27516] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:16 +0300] [27516] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:17 +0300] [27570] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:29:17 +0300] [27570] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:17 +0300] [27570] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:17 +0300] [27516] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:29:18 +0300] [27570] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:18 +0300] [27570] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:19 +0300] [27570] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:19 +0300] [27570] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:20 +0300] [27570] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:20 +0300] [27570] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:21 +0300] [27570] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:21 +0300] [27570] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:22 +0300] [27570] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:29:32 +0300] [27715] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:29:32 +0300] [27715] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:32 +0300] [27715] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:33 +0300] [27715] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:33 +0300] [27715] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:34 +0300] [27715] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:34 +0300] [27715] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:35 +0300] [27715] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:35 +0300] [27715] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:36 +0300] [27715] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:36 +0300] [27715] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:37 +0300] [27715] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:29:47 +0300] [27838] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:29:47 +0300] [27838] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:47 +0300] [27838] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:48 +0300] [27838] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:48 +0300] [27838] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:49 +0300] [27838] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:49 +0300] [27838] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:50 +0300] [27838] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:50 +0300] [27838] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:51 +0300] [27838] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:51 +0300] [27838] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:52 +0300] [27838] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:29:53 +0300] [27888] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:29:53 +0300] [27888] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:53 +0300] [27888] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:54 +0300] [27888] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:54 +0300] [27888] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:55 +0300] [27888] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:55 +0300] [27888] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:56 +0300] [27888] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:56 +0300] [27888] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:57 +0300] [27888] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:29:57 +0300] [27888] [ERROR] Retrying in 1 second.
[2025-09-08 16:29:58 +0300] [27888] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:30:02 +0300] [27963] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:30:02 +0300] [27963] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:02 +0300] [27963] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:03 +0300] [27963] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:03 +0300] [27963] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:04 +0300] [27963] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:04 +0300] [27963] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:05 +0300] [27963] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:05 +0300] [27963] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:06 +0300] [27963] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:06 +0300] [27963] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:07 +0300] [27963] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:30:17 +0300] [28095] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:30:17 +0300] [28095] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:17 +0300] [28095] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:18 +0300] [28095] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:18 +0300] [28095] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:19 +0300] [28095] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:19 +0300] [28095] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:20 +0300] [28095] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:20 +0300] [28095] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:21 +0300] [28095] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:21 +0300] [28095] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:22 +0300] [28095] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:30:33 +0300] [28183] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:30:33 +0300] [28183] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:33 +0300] [28183] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:34 +0300] [28183] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:34 +0300] [28183] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:35 +0300] [28183] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:35 +0300] [28183] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:36 +0300] [28183] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:36 +0300] [28183] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:37 +0300] [28183] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:37 +0300] [28183] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:38 +0300] [28183] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:30:48 +0300] [28358] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:30:48 +0300] [28358] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:48 +0300] [28358] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:49 +0300] [28358] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:49 +0300] [28358] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:50 +0300] [28358] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:50 +0300] [28358] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:51 +0300] [28358] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:51 +0300] [28358] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:52 +0300] [28358] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:30:52 +0300] [28358] [ERROR] Retrying in 1 second.
[2025-09-08 16:30:53 +0300] [28358] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:31:03 +0300] [28453] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:31:03 +0300] [28453] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:03 +0300] [28453] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:04 +0300] [28453] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:04 +0300] [28453] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:05 +0300] [28453] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:05 +0300] [28453] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:06 +0300] [28453] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:06 +0300] [28453] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:07 +0300] [28453] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:07 +0300] [28453] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:08 +0300] [28453] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:31:18 +0300] [28582] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:31:18 +0300] [28582] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:18 +0300] [28582] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:19 +0300] [28582] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:19 +0300] [28582] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:20 +0300] [28582] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:20 +0300] [28582] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:21 +0300] [28582] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:21 +0300] [28582] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:22 +0300] [28582] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:22 +0300] [28582] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:23 +0300] [28582] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:31:34 +0300] [28685] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:31:34 +0300] [28685] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:34 +0300] [28685] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:35 +0300] [28685] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:35 +0300] [28685] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:36 +0300] [28685] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:36 +0300] [28685] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:37 +0300] [28685] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:37 +0300] [28685] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:38 +0300] [28685] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:38 +0300] [28685] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:39 +0300] [28685] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:31:39 +0300] [28710] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:31:39 +0300] [28710] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:39 +0300] [28710] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:40 +0300] [28710] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:40 +0300] [28710] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:41 +0300] [28710] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:41 +0300] [28710] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:42 +0300] [28710] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:42 +0300] [28710] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:43 +0300] [28710] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:43 +0300] [28710] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:44 +0300] [28710] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:31:54 +0300] [28840] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:31:54 +0300] [28840] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:54 +0300] [28840] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:55 +0300] [28840] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:55 +0300] [28840] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:56 +0300] [28840] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:56 +0300] [28840] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:57 +0300] [28840] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:57 +0300] [28840] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:58 +0300] [28840] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:31:58 +0300] [28840] [ERROR] Retrying in 1 second.
[2025-09-08 16:31:59 +0300] [28840] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:32:09 +0300] [28946] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:32:09 +0300] [28946] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:09 +0300] [28946] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:10 +0300] [28946] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:10 +0300] [28946] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:11 +0300] [28946] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:11 +0300] [28946] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:12 +0300] [28946] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:12 +0300] [28946] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:13 +0300] [28946] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:13 +0300] [28946] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:14 +0300] [28946] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:32:25 +0300] [29018] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:32:25 +0300] [29018] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:25 +0300] [29018] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:26 +0300] [29018] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:26 +0300] [29018] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:27 +0300] [29018] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:27 +0300] [29018] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:28 +0300] [29018] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:28 +0300] [29018] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:29 +0300] [29018] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:29 +0300] [29018] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:30 +0300] [29018] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:32:40 +0300] [29111] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:32:40 +0300] [29111] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:40 +0300] [29111] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:41 +0300] [29111] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:41 +0300] [29111] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:42 +0300] [29111] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:42 +0300] [29111] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:43 +0300] [29111] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:43 +0300] [29111] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:44 +0300] [29111] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:44 +0300] [29111] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:45 +0300] [29111] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:32:55 +0300] [29226] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:32:55 +0300] [29226] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:55 +0300] [29226] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:56 +0300] [29226] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:56 +0300] [29226] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:57 +0300] [29226] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:57 +0300] [29226] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:58 +0300] [29226] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:58 +0300] [29226] [ERROR] Retrying in 1 second.
[2025-09-08 16:32:59 +0300] [29226] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:32:59 +0300] [29226] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:00 +0300] [29226] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:33:10 +0300] [29380] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:33:10 +0300] [29380] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:10 +0300] [29380] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:11 +0300] [29380] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:11 +0300] [29380] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:12 +0300] [29380] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:12 +0300] [29380] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:13 +0300] [29380] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:13 +0300] [29380] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:14 +0300] [29380] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:14 +0300] [29380] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:15 +0300] [29380] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:33:26 +0300] [29581] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:33:26 +0300] [29581] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:26 +0300] [29581] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:27 +0300] [29581] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:27 +0300] [29581] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:28 +0300] [29581] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:28 +0300] [29581] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:29 +0300] [29581] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:29 +0300] [29581] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:30 +0300] [29581] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2025-09-08 16:33:30 +0300] [29581] [ERROR] Retrying in 1 second.
[2025-09-08 16:33:31 +0300] [29581] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2025-09-08 16:33:41 +0300] [29740] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:33:41 +0300] [29740] [INFO] Listening at: http://127.0.0.1:5000 (29740)
[2025-09-08 16:33:41 +0300] [29740] [INFO] Using worker: sync
[2025-09-08 16:33:41 +0300] [29744] [INFO] Booting worker with pid: 29744
[2025-09-08 16:33:41 +0300] [29748] [INFO] Booting worker with pid: 29748
[2025-09-08 16:33:50,023] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:34:34,593] INFO in app: POST request to login from 127.0.0.1
[2025-09-08 16:34:34,594] INFO in app: Login attempt for email: gena12m@gmail.com
[2025-09-08 16:34:34,602] WARNING in app: Failed login attempt for email: gena12m@gmail.com
[2025-09-08 16:34:34,906] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:34:40,371] INFO in app: POST request to login from 127.0.0.1
[2025-09-08 16:34:40,371] INFO in app: Login attempt for email: gena12m@gmail.com
[2025-09-08 16:34:40,372] WARNING in app: Failed login attempt for email: gena12m@gmail.com
[2025-09-08 16:34:40,398] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:34:42,912] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:35:05,407] INFO in app: POST request to register from 127.0.0.1
[2025-09-08 16:35:05,407] INFO in app: Registration attempt for email: gena12m@gmail.com, name: ГенаДемо
[2025-09-08 16:35:05,509] INFO in app: Successful registration for user: gena12m@gmail.com (ID: 1)
[2025-09-08 16:35:05,542] ERROR in app: Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1155, in dashboard
    return render_template(
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/admin/crystall-budget/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/admin/crystall-budget/templates/base.html", line 222, in top-level template code
    {% block content %}{% endblock %}
  File "/home/admin/crystall-budget/templates/dashboard.html", line 318, in block 'content'
    {% include 'partials/modals_dashboard.html' %}
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: partials/modals_dashboard.html
[2025-09-08 16:35:05,547] ERROR in app: 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
[2025-09-08 16:35:16,561] ERROR in app: Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1155, in dashboard
    return render_template(
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/admin/crystall-budget/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/admin/crystall-budget/templates/base.html", line 222, in top-level template code
    {% block content %}{% endblock %}
  File "/home/admin/crystall-budget/templates/dashboard.html", line 318, in block 'content'
    {% include 'partials/modals_dashboard.html' %}
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: partials/modals_dashboard.html
[2025-09-08 16:35:16,563] ERROR in app: 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
[2025-09-08 16:35:19,343] ERROR in app: Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1155, in dashboard
    return render_template(
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/admin/crystall-budget/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/admin/crystall-budget/templates/base.html", line 222, in top-level template code
    {% block content %}{% endblock %}
  File "/home/admin/crystall-budget/templates/dashboard.html", line 318, in block 'content'
    {% include 'partials/modals_dashboard.html' %}
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: partials/modals_dashboard.html
[2025-09-08 16:35:19,343] ERROR in app: 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
[2025-09-08 16:45:31 +0300] [29744] [INFO] Worker exiting (pid: 29744)
[2025-09-08 16:45:31 +0300] [29748] [INFO] Worker exiting (pid: 29748)
[2025-09-08 16:45:31 +0300] [29740] [INFO] Handling signal: term
[2025-09-08 16:45:31 +0300] [29740] [INFO] Shutting down: Master
[2025-09-08 16:45:32 +0300] [32417] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:45:32 +0300] [32417] [INFO] Listening at: http://127.0.0.1:5000 (32417)
[2025-09-08 16:45:32 +0300] [32417] [INFO] Using worker: sync
[2025-09-08 16:45:32 +0300] [32418] [INFO] Booting worker with pid: 32418
[2025-09-08 16:45:32 +0300] [32419] [INFO] Booting worker with pid: 32419
[2025-09-08 16:45:42,051] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:45:45,293] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:45:46,049] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:45:53,862] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:45:55,911] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:45:56,599] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:57:21 +0300] [32419] [INFO] Worker exiting (pid: 32419)
[2025-09-08 16:57:21 +0300] [32418] [INFO] Worker exiting (pid: 32418)
[2025-09-08 16:57:21 +0300] [32417] [INFO] Handling signal: term
[2025-09-08 16:57:22 +0300] [32417] [INFO] Shutting down: Master
[2025-09-08 16:57:22 +0300] [2432] [INFO] Starting gunicorn 21.2.0
[2025-09-08 16:57:22 +0300] [2432] [INFO] Listening at: http://127.0.0.1:5000 (2432)
[2025-09-08 16:57:22 +0300] [2432] [INFO] Using worker: sync
[2025-09-08 16:57:22 +0300] [2464] [INFO] Booting worker with pid: 2464
[2025-09-08 16:57:22 +0300] [2465] [INFO] Booting worker with pid: 2465
[2025-09-08 16:57:33,031] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:57:34,532] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:57:36,456] INFO in app: User logout: gena12m@gmail.com
[2025-09-08 16:57:36,511] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:57:38,621] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:57:47,504] INFO in app: POST request to login from 127.0.0.1
[2025-09-08 16:57:47,504] INFO in app: Login attempt for email: gena12m@gmail.com
[2025-09-08 16:57:47,605] INFO in app: Successful login for user: gena12m@gmail.com (ID: 1)
[2025-09-08 16:57:48,000] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 16:57:51,569] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:08:14 +0300] [2464] [INFO] Worker exiting (pid: 2464)
[2025-09-08 17:08:14 +0300] [2465] [INFO] Worker exiting (pid: 2465)
[2025-09-08 17:08:14 +0300] [2432] [INFO] Handling signal: term
[2025-09-08 17:08:14 +0300] [2432] [INFO] Shutting down: Master
[2025-09-08 17:08:14 +0300] [4953] [INFO] Starting gunicorn 21.2.0
[2025-09-08 17:08:14 +0300] [4953] [INFO] Listening at: http://127.0.0.1:5000 (4953)
[2025-09-08 17:08:14 +0300] [4953] [INFO] Using worker: sync
[2025-09-08 17:08:14 +0300] [4954] [INFO] Booting worker with pid: 4954
[2025-09-08 17:08:14 +0300] [4955] [INFO] Booting worker with pid: 4955
[2025-09-08 17:08:59,798] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:09:01,541] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:09:43,447] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:09:43,995] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:09:44,729] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:16:40 +0300] [4955] [INFO] Worker exiting (pid: 4955)
[2025-09-08 17:16:40 +0300] [4954] [INFO] Worker exiting (pid: 4954)
[2025-09-08 17:16:40 +0300] [4953] [INFO] Handling signal: term
[2025-09-08 17:16:40 +0300] [4953] [INFO] Shutting down: Master
[2025-09-08 17:16:40 +0300] [6905] [INFO] Starting gunicorn 21.2.0
[2025-09-08 17:16:40 +0300] [6905] [INFO] Listening at: http://127.0.0.1:5000 (6905)
[2025-09-08 17:16:40 +0300] [6905] [INFO] Using worker: sync
[2025-09-08 17:16:40 +0300] [6906] [INFO] Booting worker with pid: 6906
[2025-09-08 17:16:40 +0300] [6907] [INFO] Booting worker with pid: 6907
[2025-09-08 17:16:44,044] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:16:46,834] INFO in app: User logout: gena12m@gmail.com
[2025-09-08 17:16:47,484] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:16:48,136] INFO in app: POST request to login from 127.0.0.1
[2025-09-08 17:16:48,137] INFO in app: Login attempt for email: gena12m@gmail.com
[2025-09-08 17:16:48,233] INFO in app: Successful login for user: gena12m@gmail.com (ID: 1)
[2025-09-08 17:16:48,624] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:30:20 +0300] [6907] [INFO] Worker exiting (pid: 6907)
[2025-09-08 17:30:20 +0300] [6906] [INFO] Worker exiting (pid: 6906)
[2025-09-08 17:30:20 +0300] [6905] [INFO] Handling signal: term
[2025-09-08 17:30:20 +0300] [6905] [ERROR] Worker (pid:6906) was sent SIGTERM!
[2025-09-08 17:30:20 +0300] [6905] [ERROR] Worker (pid:6907) was sent SIGTERM!
[2025-09-08 17:30:20 +0300] [6905] [INFO] Shutting down: Master
[2025-09-08 17:32:13 +0300] [10223] [INFO] Starting gunicorn 21.2.0
[2025-09-08 17:32:13 +0300] [10223] [INFO] Listening at: http://127.0.0.1:5000 (10223)
[2025-09-08 17:32:13 +0300] [10223] [INFO] Using worker: sync
[2025-09-08 17:32:13 +0300] [10224] [INFO] Booting worker with pid: 10224
[2025-09-08 17:32:13 +0300] [10225] [INFO] Booting worker with pid: 10225
[2025-09-08 17:32:15 +0300] [10224] [INFO] Worker exiting (pid: 10224)
[2025-09-08 17:32:15 +0300] [10225] [INFO] Worker exiting (pid: 10225)
[2025-09-08 17:32:15 +0300] [10223] [INFO] Handling signal: term
[2025-09-08 17:32:15 +0300] [10223] [INFO] Shutting down: Master
[2025-09-08 17:32:16 +0300] [10248] [INFO] Starting gunicorn 21.2.0
[2025-09-08 17:32:16 +0300] [10248] [INFO] Listening at: http://127.0.0.1:5000 (10248)
[2025-09-08 17:32:16 +0300] [10248] [INFO] Using worker: sync
[2025-09-08 17:32:16 +0300] [10255] [INFO] Booting worker with pid: 10255
[2025-09-08 17:32:16 +0300] [10256] [INFO] Booting worker with pid: 10256
[2025-09-08 17:32:19,759] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:32:20,658] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:32:21,721] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:32:27,082] INFO in app: POST request to create_shared_budget from 127.0.0.1
[2025-09-08 17:32:27,119] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:32:28,984] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:32:32,350] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:32:32,794] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:01,323] INFO in app: POST request to categories_add from 127.0.0.1
[2025-09-08 17:33:01,962] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:05,890] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:16,869] INFO in app: POST request to categories_delete from 127.0.0.1
[2025-09-08 17:33:16,904] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:23,737] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:28,417] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:33,302] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:33,929] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:42,794] INFO in app: POST request to sources_add from 127.0.0.1
[2025-09-08 17:33:42,855] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:44,080] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:53,818] INFO in app: POST request to categories_add from 127.0.0.1
[2025-09-08 17:33:54,468] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:58,571] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:33:59,482] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:34:02,085] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:34:04,969] INFO in app: POST request to categories_delete from 127.0.0.1
[2025-09-08 17:34:05,324] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:34:47,651] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:34:51,059] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:35:02,694] INFO in app: POST request to categories_add from 127.0.0.1
[2025-09-08 17:35:03,040] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:35:06,479] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:35:09,699] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:35:18,868] INFO in app: POST request to income_add from 127.0.0.1
[2025-09-08 17:35:18,905] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:35:21,627] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:35:25,958] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:35:29,024] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:26,373] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:26,767] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:27,412] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:27,994] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:28,414] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:29,787] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:30,764] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:36:31,399] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:41:47,897] INFO in app: POST request to set_currency from 127.0.0.1
[2025-09-08 17:43:49 +0300] [10248] [CRITICAL] WORKER TIMEOUT (pid:10255)
[2025-09-08 17:43:49 +0300] [10255] [INFO] Worker exiting (pid: 10255)
[2025-09-08 17:43:49 +0300] [10248] [ERROR] Worker (pid:10255) exited with code 1
[2025-09-08 17:43:49 +0300] [10248] [ERROR] Worker (pid:10255) exited with code 1.
[2025-09-08 17:43:49 +0300] [12567] [INFO] Booting worker with pid: 12567
[2025-09-08 17:49:42,630] WARNING in app: 404 Not Found: http://localhost:5000/.well-known/appspecific/com.chrome.devtools.json - 127.0.0.1
[2025-09-08 17:49:42,641] WARNING in app: 404 Not Found: http://localhost:5000/static/js/bootstrap.bundle.min.js.map - 127.0.0.1
